remote_theme: pfgithub/cayman
custom_buttons:
  -
    title: SpoilerBot
    url: https://pfgithub.github.io/spoilerbot/
  -
    title: Atom Markdown Editor
    url: https://github.com/pfgithub/atom-markdown-editor
